server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/era_process?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: zhu123456
    driver-class-name: com.mysql.cj.jdbc.Driver